[advisories]
yanked = "deny"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
