[package]
name = "libaprs-engine-downstream-smoke"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
libaprs-engine = "0.1.5"
aprs-transport-file = "0.1.5"
aprs-transport-tcp = "0.1.5"
aprs-transport-aprs-is = "0.1.5"
aprs-transport-async = "0.1.5"
aprs-transport-ax25 = "0.1.5"
aprs-transport-channel = "0.1.5"
aprs-transport-corpus = "0.1.5"
aprs-transport-file-watch = "0.1.5"
aprs-transport-http = "0.1.5"
aprs-transport-kiss = "0.1.5"
aprs-transport-mqtt = "0.1.5"
aprs-transport-serial = "0.1.5"
aprs-transport-udp = "0.1.5"
