[package]
name = "libaprs-engine-downstream-smoke"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
libaprs-engine = "1.0.0"
aprs-transport-file = "1.0.0"
aprs-transport-tcp = "1.0.0"
aprs-transport-aprs-is = "1.0.0"
aprs-transport-async = "1.0.0"
aprs-transport-ax25 = "1.0.0"
aprs-transport-channel = "1.0.0"
aprs-transport-corpus = "1.0.0"
aprs-transport-file-watch = "1.0.0"
aprs-transport-http = "1.0.0"
aprs-transport-kiss = "1.0.0"
aprs-transport-mqtt = "1.0.0"
aprs-transport-serial = "1.0.0"
aprs-transport-udp = "1.0.0"
